apiVersion: v1
kind: Service
metadata:
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: service-port-name
      port: 80
      protocol: TCP
  selector:
    deployment-label-key: service-name-loadbalancer