apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-angular
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : label-value  
    spec:
      containers:
        - name: deploment-container-angular
          image: fury/angular-app:latest
          ports:
            - containerPort: 80